### ISSUE TITLE
uri-handler problem

### ISSUE THREAD

**Issue by pavroo** [v1cont/yad#103]
Hi
Built 7.1 on Debian testing amd64. After upgrade, one of my applications which uses the --uri-handler stopped launching custom commands.
The answer is: The URL can’t be shown
Any clue, please?
Regards
pavroo

**Comment by v1cont** [comment]
check 171c9ca please

**Comment by TeHMoroS** [comment]
@pavroo Check if the handler file has the executable privilege. From what I understand from commit 90ab883, instead of opening the script via the "open-command", it is now ran directly (that's an assumption at this time, because I haven't yet looked an the `run_command_async` function, but it seems some potentially breaking changes were introduced during the comment mentioned above. Not necessarily a code bug, but rather a behavioural one ("open_command" handling bad privileges, while direct launching does not - basically a default behaviour on *nix systems).

Let me know if that was of any help. I'll set my environment up for some bisecting if needed. I want to keep everything here because if it's either a bug or us missing something, I want to keep a record for anyone bumping into the same problem.

**Comment by pavroo** [comment]
Just build it from git with commit e9957f8 which fixed the problem, thanks.
